#FROM mcr.microsoft.com/dotnet/core/runtime:3.1.5-bionic AS base
FROM ubuntu:20.04
WORKDIR /app
COPY ./build .

#Default Container Port 5001 will be used.
ARG DEFAULTPORT=5001

EXPOSE $DEFAULTPORT

ENV DBSERVER=""
ENV DBUSER=""
ENV DBPASS=""
ENV DBNAME=""
ENV PORT=$DEFAULTPORT

# Install common dependencies
RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    tzdata \
    curl \
    libicu-dev \
    wget && \
    rm -rf /var/lib/apt/lists/*

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
LABEL com.centurylinklabs.watchtower.enable="true"

COPY Server/entrypoint.sh .

ENTRYPOINT ["/app/entrypoint.sh"]


