FROM mcr.microsoft.com/dotnet/core/runtime:3.1.5-bionic AS base
WORKDIR /app
COPY ./build .

#Default Container Port 5001 will be used.
ARG DEFAULTPORT=5001

EXPOSE $DEFAULTPORT

ENV DBSERVER=""
ENV DBUSER=""
ENV DBPASS=""
ENV DBNAME=""
ENV PORT=$DEFAULTPORT

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ["dotnet", "HolidayShowWeb.dll"]


