stages:
  - build

before_script:
  - chmod +x scripts/docker/*.sh
  # - echo $CI_JOB_TOKEN | docker login -u traviswhidden --password-stdin

# ===== BUILD JOBS

beta_x86_64:
  stage: build
  only:
    refs:
      - master
  except:
    - tags
  script:
    - cd scripts/docker/core-svr
    - npm run build-x64-beta
    - npm run push-x64-beta
    - exit 0
  allow_failure: false
  tags:
    - linux


prod_x86_64:
  stage: build
  only:
    variables:
      - $CI_COMMIT_TITLE =~ /^Release Server v[0-9\.].*$/ 
  except:
    - tags
  script:
    - scripts/docker/build.sh -d core-svr -a x64
    - scripts/docker/push.sh -d core-svr -a x64
    - exit 0
  allow_failure: false
  tags:
    - linux


