FROM arm32v7/ubuntu:bionic AS base
WORKDIR /app
COPY ./build .
COPY ./platform /

#Default Container Port 5555 will be used.
ARG DEFAULTPORT=5555
ARG DEFAULTSTORAGE='/data'

EXPOSE $DEFAULTPORT

ENV DEVICEID=
ENV SERVER=
ENV PORT=$DEFAULTPORT
ENV STORAGE=$DEFAULTSTORAGE
ENV PORT=$DEFAULTPORT
ENV DOTNET_RUNNING_IN_CONTAINER=true

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#QT is required for the relay plate - this is a big dependancy, and the library should later be staticly linked. 
# amixer will use the RP3 analog output jack instead of the hdmi (default)
# sox will not play m4a files, so switching to mplayer
RUN apt-get update && \
    apt-get install -y liblttng-ust0 libcurl3 libssl1.0.0 libkrb5-3 zlib1g libicu60 qt5-default mplayer alsa-utils && \
	rm -rf /var/lib/apt/lists/*

# Enable / Disable Auto Updates
LABEL com.centurylinklabs.watchtower.enable="true"

COPY Server/entrypoint.sh .
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]