#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace HolidayShow.Data
{
    /// <summary>
    /// The class representing the dbo.DeviceIoPorts table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.DeviceIoPorts")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(HolidayShow.Data.DeviceIoPorts.Metadata))]
    [System.Data.Services.Common.DataServiceKey("DeviceIoPortId")]
    [System.Diagnostics.DebuggerDisplay("DeviceIoPortId: {DeviceIoPortId}")]
    public partial class DeviceIoPorts
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="DeviceIoPorts"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static DeviceIoPorts()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceIoPorts"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public DeviceIoPorts()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            _devices = default(System.Data.Linq.EntityRef<Devices>);
            _devicePatternSequencesList = new System.Data.Linq.EntitySet<DevicePatternSequences>(OnDevicePatternSequencesListAdd, OnDevicePatternSequencesListRemove);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _deviceIoPortId = default(int);

        /// <summary>
        /// Gets the DeviceIoPortId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "DeviceIoPortId", Storage = "_deviceIoPortId", DbType = "int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int DeviceIoPortId
        {
            get { return _deviceIoPortId; }
            set
            {
                if (_deviceIoPortId != value)
                {
                    OnDeviceIoPortIdChanging(value);
                    SendPropertyChanging("DeviceIoPortId");
                    _deviceIoPortId = value;
                    SendPropertyChanged("DeviceIoPortId");
                    OnDeviceIoPortIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _deviceId;

        /// <summary>
        /// Gets or sets the DeviceId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "DeviceId", Storage = "_deviceId", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int DeviceId
        {
            get { return _deviceId; }
            set
            {
                if (_deviceId != value)
                {
                    if (_devices.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnDeviceIdChanging(value);
                    SendPropertyChanging("DeviceId");
                    _deviceId = value;
                    SendPropertyChanged("DeviceId");
                    OnDeviceIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _commandPin;

        /// <summary>
        /// Gets or sets the CommandPin column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "CommandPin", Storage = "_commandPin", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int CommandPin
        {
            get { return _commandPin; }
            set
            {
                if (_commandPin != value)
                {
                    OnCommandPinChanging(value);
                    SendPropertyChanging("CommandPin");
                    _commandPin = value;
                    SendPropertyChanged("CommandPin");
                    OnCommandPinChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _description;

        /// <summary>
        /// Gets or sets the Description column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Description", Storage = "_description", DbType = "nvarchar(50) NOT NULL", CanBeNull = false, UpdateCheck = System.Data.Linq.Mapping.UpdateCheck.Never)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    OnDescriptionChanging(value);
                    SendPropertyChanging("Description");
                    _description = value;
                    SendPropertyChanged("Description");
                    OnDescriptionChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool _isNotVisable;

        /// <summary>
        /// Gets or sets the IsNotVisable column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IsNotVisable", Storage = "_isNotVisable", DbType = "bit NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public bool IsNotVisable
        {
            get { return _isNotVisable; }
            set
            {
                if (_isNotVisable != value)
                {
                    OnIsNotVisableChanging(value);
                    SendPropertyChanging("IsNotVisable");
                    _isNotVisable = value;
                    SendPropertyChanged("IsNotVisable");
                    OnIsNotVisableChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool _isDanger;

        /// <summary>
        /// Gets or sets the IsDanger column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IsDanger", Storage = "_isDanger", DbType = "bit NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public bool IsDanger
        {
            get { return _isDanger; }
            set
            {
                if (_isDanger != value)
                {
                    OnIsDangerChanging(value);
                    SendPropertyChanging("IsDanger");
                    _isDanger = value;
                    SendPropertyChanged("IsDanger");
                    OnIsDangerChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<Devices> _devices;

        /// <summary>
        /// Gets or sets the <see cref="Devices"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "Devices_DeviceIoPorts", Storage = "_devices", ThisKey = "DeviceId", OtherKey = "DeviceId", IsForeignKey = true, DeleteRule = "CASCADE")]
        [System.Runtime.Serialization.DataMember(Order = 7, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Devices Devices
        {
            get { return (serializing && !_devices.HasLoadedOrAssignedValue) ? null : _devices.Entity; }
            set
            {
                Devices previousValue = _devices.Entity;
                if (previousValue != value || _devices.HasLoadedOrAssignedValue == false)
                {
                    OnDevicesChanging(value);
                    SendPropertyChanging("Devices");
                    if (previousValue != null)
                    {
                        _devices.Entity = null;
                        previousValue.DeviceIoPortsList.Remove(this);
                    }
                    _devices.Entity = value;
                    if (value != null)
                    {
                        value.DeviceIoPortsList.Add(this);
                        _deviceId = value.DeviceId;
                    }
                    else
                    {
                        _deviceId = default(int);
                    }
                    SendPropertyChanged("Devices");
                    OnDevicesChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntitySet<DevicePatternSequences> _devicePatternSequencesList;

        /// <summary>
        /// Gets or sets the <see cref="DevicePatternSequences"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "DeviceIoPorts_DevicePatternSequences", Storage = "_devicePatternSequencesList", ThisKey = "DeviceIoPortId", OtherKey = "DeviceIoPortId")]
        [System.Runtime.Serialization.DataMember(Order=8, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Data.Linq.EntitySet<DevicePatternSequences> DevicePatternSequencesList
        {
            get { return (serializing && !_devicePatternSequencesList.HasLoadedOrAssignedValues) ? null : _devicePatternSequencesList; }
            set { _devicePatternSequencesList.Assign(value); }
        }
        
        

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void OnDevicePatternSequencesListAdd(DevicePatternSequences entity)
        {
            SendPropertyChanging(null);
            entity.DeviceIoPorts = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void OnDevicePatternSequencesListRemove(DevicePatternSequences entity)
        {
            SendPropertyChanging(null);
            entity.DeviceIoPorts = null;
            SendPropertyChanged(null);
        }
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="DeviceIoPortId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDeviceIoPortIdChanging(int value);
        /// <summary>Called after <see cref="DeviceIoPortId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDeviceIoPortIdChanged();
        /// <summary>Called when <see cref="DeviceId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDeviceIdChanging(int value);
        /// <summary>Called after <see cref="DeviceId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDeviceIdChanged();
        /// <summary>Called when <see cref="CommandPin"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCommandPinChanging(int value);
        /// <summary>Called after <see cref="CommandPin"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCommandPinChanged();
        /// <summary>Called when <see cref="Description"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDescriptionChanging(string value);
        /// <summary>Called after <see cref="Description"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDescriptionChanged();
        /// <summary>Called when <see cref="IsNotVisable"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIsNotVisableChanging(bool value);
        /// <summary>Called after <see cref="IsNotVisable"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIsNotVisableChanged();
        /// <summary>Called when <see cref="IsDanger"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIsDangerChanging(bool value);
        /// <summary>Called after <see cref="IsDanger"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIsDangerChanged();
        /// <summary>Called when <see cref="Devices"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDevicesChanging(Devices value);
        /// <summary>Called after <see cref="Devices"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnDevicesChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="DeviceIoPorts"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="DeviceIoPorts"/> instance.</param>
        /// <returns>An instance of <see cref="DeviceIoPorts"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static DeviceIoPorts FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(DeviceIoPorts));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as DeviceIoPorts;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="DeviceIoPorts"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="DeviceIoPorts"/> instance.</param>
        /// <returns>An instance of <see cref="DeviceIoPorts"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static DeviceIoPorts FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(DeviceIoPorts));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as DeviceIoPorts;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public DeviceIoPorts Clone()
        {
            return (DeviceIoPorts)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _devices = Detach(_devices);
            _devicePatternSequencesList = Detach(_devicePatternSequencesList, OnDevicePatternSequencesListAdd, OnDevicePatternSequencesListRemove);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
