#FROM mcr.microsoft.com/dotnet/core/runtime:3.1.5-bionic AS base
FROM mcr.microsoft.com/dotnet/runtime:5.0.11-focal AS base
WORKDIR /app
COPY ./build .
ENV DEBIAN_FRONTEND noninteractive
#Default Container Port 5001 will be used.
ARG DEFAULTPORT=5555

EXPOSE $DEFAULTPORT

ENV DBSERVER=""
ENV DBUSER=""
ENV DBPASS=""
ENV DBNAME=""
ENV PORT=$DEFAULTPORT

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

ENV TZ "America/Los_Angeles"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY Server/entrypoint.sh .

ENTRYPOINT ["/app/entrypoint.sh"]


