#pragma warning disable 1591
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Linq;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;

namespace HolidayShow.Data
{
    /// <summary>
    /// The query extension class for Devices.
    /// </summary>
    public static partial class DevicesExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static HolidayShow.Data.Devices GetByKey(this IQueryable<HolidayShow.Data.Devices> queryable, int deviceId)
        {
            var entity = queryable as System.Data.Linq.Table<HolidayShow.Data.Devices>;
            if (entity != null && entity.Context.LoadOptions == null)
                return Query.GetByKey.Invoke((HolidayShow.Data.HolidayShowDataContext)entity.Context, deviceId);

            return queryable.FirstOrDefault(d => d.DeviceId == deviceId);
        }

        /// <summary>
        /// Immediately deletes the entity by the primary key from the underlying data source with a single delete command.
        /// </summary>
        /// <param name="table">Represents a table for a particular type in the underlying database containing rows are to be deleted.</param>
        /// <returns>The number of rows deleted from the database.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static int Delete(this System.Data.Linq.Table<HolidayShow.Data.Devices> table, int deviceId)
        {
            return table.Delete(d => d.DeviceId == deviceId);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceId">DeviceId to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByDeviceId(this IQueryable<HolidayShow.Data.Devices> queryable, int deviceId)
        {
            return queryable.Where(d => d.DeviceId == deviceId);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceId">DeviceId to search for. This is on the right side of the operator.</param>
        /// <param name="comparisonOperator">The comparison operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByDeviceId(this IQueryable<HolidayShow.Data.Devices> queryable, ComparisonOperator comparisonOperator, int deviceId)
        {
            switch (comparisonOperator)
            {
                case ComparisonOperator.GreaterThan:
                    return queryable.Where(d => d.DeviceId > deviceId);
                case ComparisonOperator.GreaterThanOrEquals:
                    return queryable.Where(d => d.DeviceId >= deviceId);
                case ComparisonOperator.LessThan:
                    return queryable.Where(d => d.DeviceId < deviceId);
                case ComparisonOperator.LessThanOrEquals:
                    return queryable.Where(d => d.DeviceId <= deviceId);
                case ComparisonOperator.NotEquals:
                    return queryable.Where(d => d.DeviceId != deviceId);
                default:
                    return queryable.Where(d => d.DeviceId == deviceId);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceId">DeviceId to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByDeviceId(this IQueryable<HolidayShow.Data.Devices> queryable, int deviceId, params int[] additionalValues)
        {
            var deviceIdList = new List<int> { deviceId };

            if (additionalValues != null)
                deviceIdList.AddRange(additionalValues);

            if (deviceIdList.Count == 1)
                return queryable.ByDeviceId(deviceIdList[0]);

            return queryable.ByDeviceId(deviceIdList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByDeviceId(this IQueryable<HolidayShow.Data.Devices> queryable, IEnumerable<int> values)
        {
            return queryable.Where(d => values.Contains(d.DeviceId));
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.Name"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="name">Name to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByName(this IQueryable<HolidayShow.Data.Devices> queryable, string name)
        {
            return queryable.Where(d => d.Name == name);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.Name"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="name">Name to search for.</param>
        /// <param name="containmentOperator">The containment operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByName(this IQueryable<HolidayShow.Data.Devices> queryable, ContainmentOperator containmentOperator, string name)
        {
            if (name == null && containmentOperator != ContainmentOperator.Equals && containmentOperator != ContainmentOperator.NotEquals)
                throw new ArgumentNullException("name", "Parameter 'name' cannot be null with the specified ContainmentOperator.  Parameter 'containmentOperator' must be ContainmentOperator.Equals or ContainmentOperator.NotEquals to support null.");

            switch (containmentOperator)
            {
                case ContainmentOperator.Contains:
                    return queryable.Where(d => d.Name.Contains(name));
                case ContainmentOperator.StartsWith:
                    return queryable.Where(d => d.Name.StartsWith(name));
                case ContainmentOperator.EndsWith:
                    return queryable.Where(d => d.Name.EndsWith(name));
                case ContainmentOperator.NotContains:
                    return queryable.Where(d => d.Name.Contains(name) == false);
                case ContainmentOperator.NotEquals:
                    return queryable.Where(d => d.Name != name);
                default:
                    return queryable.Where(d => d.Name == name);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.Name"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="name">Name to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByName(this IQueryable<HolidayShow.Data.Devices> queryable, string name, params string[] additionalValues)
        {
            var nameList = new List<string> { name };

            if (additionalValues != null)
                nameList.AddRange(additionalValues);

            if (nameList.Count == 1)
                return queryable.ByName(nameList[0]);

            return queryable.ByName(nameList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.Devices.Name"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.Devices> ByName(this IQueryable<HolidayShow.Data.Devices> queryable, IEnumerable<string> values)
        {
            return queryable.Where(d => values.Contains(d.Name));
        }

        #region Query
        /// <summary>
        /// A private class for lazy loading static compiled queries.
        /// </summary>
        private static partial class Query
        {

            [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
            internal static readonly Func<HolidayShow.Data.HolidayShowDataContext, int, HolidayShow.Data.Devices> GetByKey =
                System.Data.Linq.CompiledQuery.Compile(
                    (HolidayShow.Data.HolidayShowDataContext db, int deviceId) =>
                        db.Devices.FirstOrDefault(d => d.DeviceId == deviceId));

        }
        #endregion
    }
}
#pragma warning restore 1591
