#pragma warning disable 1591
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Linq;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;

namespace HolidayShow.Data
{
    /// <summary>
    /// The query extension class for DeviceIoPorts.
    /// </summary>
    public static partial class DeviceIoPortsExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static HolidayShow.Data.DeviceIoPorts GetByKey(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, int deviceIoPortId)
        {
            var entity = queryable as System.Data.Linq.Table<HolidayShow.Data.DeviceIoPorts>;
            if (entity != null && entity.Context.LoadOptions == null)
                return Query.GetByKey.Invoke((HolidayShow.Data.HolidayShowDataContext)entity.Context, deviceIoPortId);

            return queryable.FirstOrDefault(d => d.DeviceIoPortId == deviceIoPortId);
        }

        /// <summary>
        /// Immediately deletes the entity by the primary key from the underlying data source with a single delete command.
        /// </summary>
        /// <param name="table">Represents a table for a particular type in the underlying database containing rows are to be deleted.</param>
        /// <returns>The number of rows deleted from the database.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static int Delete(this System.Data.Linq.Table<HolidayShow.Data.DeviceIoPorts> table, int deviceIoPortId)
        {
            return table.Delete(d => d.DeviceIoPortId == deviceIoPortId);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceIoPortId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceIoPortId">DeviceIoPortId to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceIoPortId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, int deviceIoPortId)
        {
            return queryable.Where(d => d.DeviceIoPortId == deviceIoPortId);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceIoPortId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceIoPortId">DeviceIoPortId to search for. This is on the right side of the operator.</param>
        /// <param name="comparisonOperator">The comparison operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceIoPortId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, ComparisonOperator comparisonOperator, int deviceIoPortId)
        {
            switch (comparisonOperator)
            {
                case ComparisonOperator.GreaterThan:
                    return queryable.Where(d => d.DeviceIoPortId > deviceIoPortId);
                case ComparisonOperator.GreaterThanOrEquals:
                    return queryable.Where(d => d.DeviceIoPortId >= deviceIoPortId);
                case ComparisonOperator.LessThan:
                    return queryable.Where(d => d.DeviceIoPortId < deviceIoPortId);
                case ComparisonOperator.LessThanOrEquals:
                    return queryable.Where(d => d.DeviceIoPortId <= deviceIoPortId);
                case ComparisonOperator.NotEquals:
                    return queryable.Where(d => d.DeviceIoPortId != deviceIoPortId);
                default:
                    return queryable.Where(d => d.DeviceIoPortId == deviceIoPortId);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceIoPortId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceIoPortId">DeviceIoPortId to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceIoPortId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, int deviceIoPortId, params int[] additionalValues)
        {
            var deviceIoPortIdList = new List<int> { deviceIoPortId };

            if (additionalValues != null)
                deviceIoPortIdList.AddRange(additionalValues);

            if (deviceIoPortIdList.Count == 1)
                return queryable.ByDeviceIoPortId(deviceIoPortIdList[0]);

            return queryable.ByDeviceIoPortId(deviceIoPortIdList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceIoPortId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceIoPortId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, IEnumerable<int> values)
        {
            return queryable.Where(d => values.Contains(d.DeviceIoPortId));
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceId">DeviceId to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, int deviceId)
        {
            return queryable.Where(d => d.DeviceId == deviceId);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceId">DeviceId to search for. This is on the right side of the operator.</param>
        /// <param name="comparisonOperator">The comparison operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, ComparisonOperator comparisonOperator, int deviceId)
        {
            switch (comparisonOperator)
            {
                case ComparisonOperator.GreaterThan:
                    return queryable.Where(d => d.DeviceId > deviceId);
                case ComparisonOperator.GreaterThanOrEquals:
                    return queryable.Where(d => d.DeviceId >= deviceId);
                case ComparisonOperator.LessThan:
                    return queryable.Where(d => d.DeviceId < deviceId);
                case ComparisonOperator.LessThanOrEquals:
                    return queryable.Where(d => d.DeviceId <= deviceId);
                case ComparisonOperator.NotEquals:
                    return queryable.Where(d => d.DeviceId != deviceId);
                default:
                    return queryable.Where(d => d.DeviceId == deviceId);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="deviceId">DeviceId to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, int deviceId, params int[] additionalValues)
        {
            var deviceIdList = new List<int> { deviceId };

            if (additionalValues != null)
                deviceIdList.AddRange(additionalValues);

            if (deviceIdList.Count == 1)
                return queryable.ByDeviceId(deviceIdList[0]);

            return queryable.ByDeviceId(deviceIdList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.DeviceId"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDeviceId(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, IEnumerable<int> values)
        {
            return queryable.Where(d => values.Contains(d.DeviceId));
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.CommandPin"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="commandPin">CommandPin to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByCommandPin(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, int commandPin)
        {
            return queryable.Where(d => d.CommandPin == commandPin);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.CommandPin"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="commandPin">CommandPin to search for. This is on the right side of the operator.</param>
        /// <param name="comparisonOperator">The comparison operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByCommandPin(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, ComparisonOperator comparisonOperator, int commandPin)
        {
            switch (comparisonOperator)
            {
                case ComparisonOperator.GreaterThan:
                    return queryable.Where(d => d.CommandPin > commandPin);
                case ComparisonOperator.GreaterThanOrEquals:
                    return queryable.Where(d => d.CommandPin >= commandPin);
                case ComparisonOperator.LessThan:
                    return queryable.Where(d => d.CommandPin < commandPin);
                case ComparisonOperator.LessThanOrEquals:
                    return queryable.Where(d => d.CommandPin <= commandPin);
                case ComparisonOperator.NotEquals:
                    return queryable.Where(d => d.CommandPin != commandPin);
                default:
                    return queryable.Where(d => d.CommandPin == commandPin);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.CommandPin"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="commandPin">CommandPin to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByCommandPin(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, int commandPin, params int[] additionalValues)
        {
            var commandPinList = new List<int> { commandPin };

            if (additionalValues != null)
                commandPinList.AddRange(additionalValues);

            if (commandPinList.Count == 1)
                return queryable.ByCommandPin(commandPinList[0]);

            return queryable.ByCommandPin(commandPinList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.CommandPin"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByCommandPin(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, IEnumerable<int> values)
        {
            return queryable.Where(d => values.Contains(d.CommandPin));
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.Description"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="description">Description to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDescription(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, string description)
        {
            return queryable.Where(d => d.Description == description);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.Description"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="description">Description to search for.</param>
        /// <param name="containmentOperator">The containment operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDescription(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, ContainmentOperator containmentOperator, string description)
        {
            if (description == null && containmentOperator != ContainmentOperator.Equals && containmentOperator != ContainmentOperator.NotEquals)
                throw new ArgumentNullException("description", "Parameter 'description' cannot be null with the specified ContainmentOperator.  Parameter 'containmentOperator' must be ContainmentOperator.Equals or ContainmentOperator.NotEquals to support null.");

            switch (containmentOperator)
            {
                case ContainmentOperator.Contains:
                    return queryable.Where(d => d.Description.Contains(description));
                case ContainmentOperator.StartsWith:
                    return queryable.Where(d => d.Description.StartsWith(description));
                case ContainmentOperator.EndsWith:
                    return queryable.Where(d => d.Description.EndsWith(description));
                case ContainmentOperator.NotContains:
                    return queryable.Where(d => d.Description.Contains(description) == false);
                case ContainmentOperator.NotEquals:
                    return queryable.Where(d => d.Description != description);
                default:
                    return queryable.Where(d => d.Description == description);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.Description"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="description">Description to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDescription(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, string description, params string[] additionalValues)
        {
            var descriptionList = new List<string> { description };

            if (additionalValues != null)
                descriptionList.AddRange(additionalValues);

            if (descriptionList.Count == 1)
                return queryable.ByDescription(descriptionList[0]);

            return queryable.ByDescription(descriptionList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.Description"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByDescription(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, IEnumerable<string> values)
        {
            return queryable.Where(d => values.Contains(d.Description));
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsNotVisable"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="isNotVisable">IsNotVisable to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsNotVisable(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, bool isNotVisable)
        {
            return queryable.Where(d => d.IsNotVisable == isNotVisable);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsNotVisable"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="isNotVisable">IsNotVisable to search for. This is on the right side of the operator.</param>
        /// <param name="comparisonOperator">The comparison operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsNotVisable(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, ComparisonOperator comparisonOperator, bool isNotVisable)
        {
            switch (comparisonOperator)
            {
                case ComparisonOperator.GreaterThan:
                case ComparisonOperator.GreaterThanOrEquals:
                case ComparisonOperator.LessThan:
                case ComparisonOperator.LessThanOrEquals:
                    throw new ArgumentException("Parameter 'comparisonOperator' must be ComparisonOperator.Equals or ComparisonOperator.NotEquals to support bool type.", "comparisonOperator");
                case ComparisonOperator.NotEquals:
                    return queryable.Where(d => d.IsNotVisable != isNotVisable);
                default:
                    return queryable.Where(d => d.IsNotVisable == isNotVisable);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsNotVisable"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="isNotVisable">IsNotVisable to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsNotVisable(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, bool isNotVisable, params bool[] additionalValues)
        {
            var isNotVisableList = new List<bool> { isNotVisable };

            if (additionalValues != null)
                isNotVisableList.AddRange(additionalValues);

            if (isNotVisableList.Count == 1)
                return queryable.ByIsNotVisable(isNotVisableList[0]);

            return queryable.ByIsNotVisable(isNotVisableList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsNotVisable"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsNotVisable(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, IEnumerable<bool> values)
        {
            return queryable.Where(d => values.Contains(d.IsNotVisable));
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsDanger"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="isDanger">IsDanger to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsDanger(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, bool isDanger)
        {
            return queryable.Where(d => d.IsDanger == isDanger);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsDanger"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="isDanger">IsDanger to search for. This is on the right side of the operator.</param>
        /// <param name="comparisonOperator">The comparison operator.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsDanger(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, ComparisonOperator comparisonOperator, bool isDanger)
        {
            switch (comparisonOperator)
            {
                case ComparisonOperator.GreaterThan:
                case ComparisonOperator.GreaterThanOrEquals:
                case ComparisonOperator.LessThan:
                case ComparisonOperator.LessThanOrEquals:
                    throw new ArgumentException("Parameter 'comparisonOperator' must be ComparisonOperator.Equals or ComparisonOperator.NotEquals to support bool type.", "comparisonOperator");
                case ComparisonOperator.NotEquals:
                    return queryable.Where(d => d.IsDanger != isDanger);
                default:
                    return queryable.Where(d => d.IsDanger == isDanger);
            }
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsDanger"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="isDanger">IsDanger to search for.</param>
        /// <param name="additionalValues">Additional values to search for.</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsDanger(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, bool isDanger, params bool[] additionalValues)
        {
            var isDangerList = new List<bool> { isDanger };

            if (additionalValues != null)
                isDangerList.AddRange(additionalValues);

            if (isDangerList.Count == 1)
                return queryable.ByIsDanger(isDangerList[0]);

            return queryable.ByIsDanger(isDangerList);
        }

        /// <summary>
        /// Gets a query for <see cref="HolidayShow.Data.DeviceIoPorts.IsDanger"/>.
        /// </summary>
        /// <param name="queryable">Query to append where clause.</param>
        /// <param name="values">The values to search for..</param>
        /// <returns><see cref="IQueryable"/> with additional where clause.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static IQueryable<HolidayShow.Data.DeviceIoPorts> ByIsDanger(this IQueryable<HolidayShow.Data.DeviceIoPorts> queryable, IEnumerable<bool> values)
        {
            return queryable.Where(d => values.Contains(d.IsDanger));
        }

        #region Query
        /// <summary>
        /// A private class for lazy loading static compiled queries.
        /// </summary>
        private static partial class Query
        {

            [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
            internal static readonly Func<HolidayShow.Data.HolidayShowDataContext, int, HolidayShow.Data.DeviceIoPorts> GetByKey =
                System.Data.Linq.CompiledQuery.Compile(
                    (HolidayShow.Data.HolidayShowDataContext db, int deviceIoPortId) =>
                        db.DeviceIoPorts.FirstOrDefault(d => d.DeviceIoPortId == deviceIoPortId));

        }
        #endregion
    }
}
#pragma warning restore 1591
