#FROM mcr.microsoft.com/dotnet/core/runtime:3.1.5-bionic AS base
#FROM mcr.microsoft.com/dotnet/runtime:5.0.11-focal AS base
FROM ubuntu:20.04
WORKDIR /app
COPY ./build .
ENV DEBIAN_FRONTEND=noninteractive
#Default Container Port 5001 will be used.
ARG DEFAULTPORT=5555
ARG WEBSERVERPORT=5000

# TCP Port
EXPOSE $DEFAULTPORT

# Web Server Port
EXPOSE $WEBSERVERPORT

ENV DBSERVER=""
ENV DBUSER=""
ENV DBPASS=""
ENV DBNAME=""
ENV PORT=$DEFAULTPORT
ENV WEBSERVERPORT=$WEBSERVERPORT

# Install common dependencies
RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    tzdata \
    curl \
    libicu-dev \
    jq \
    wget && \
    rm -rf /var/lib/apt/lists/*

ENV TZ="America/Los_Angeles"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
LABEL com.centurylinklabs.watchtower.enable="true"

COPY Server/entrypoint.sh .
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]


