#!/bin/bash
echo "HOLIDAY SHOW CLIENT CORE"
echo "CONNECTING TO SERVER: $SERVER:$PORT"
echo "STORAGE PATH: $STORAGE"
echo "DEVICE ID: $DEVICEID"
echo "STARTING HOLIDAY SHOW CLIENT CORE..."
./HolidayShowClient.Core -s "$SERVER" -p $PORT -d $DEVICEID -a "$STORAGE"
