//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayShow.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicePatternSequences
    {
        public int DevicePatternSeqenceId { get; set; }
        public int DevicePatternId { get; set; }
        public int OnAt { get; set; }
        public int Duration { get; set; }
        public int AudioId { get; set; }
        public int DeviceIoPortId { get; set; }
    
        public virtual AudioOptions AudioOptions { get; set; }
        public virtual DeviceIoPorts DeviceIoPorts { get; set; }
        public virtual DevicePatterns DevicePatterns { get; set; }
    }
}
