//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayShow.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceIoPorts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceIoPorts()
        {
            this.DevicePatternSequences = new HashSet<DevicePatternSequences>();
        }
    
        public int DeviceIoPortId { get; set; }
        public int DeviceId { get; set; }
        public int CommandPin { get; set; }
        public string Description { get; set; }
        public bool IsNotVisable { get; set; }
        public bool IsDanger { get; set; }
    
        public virtual Devices Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevicePatternSequences> DevicePatternSequences { get; set; }
    }
}
