//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayShow.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceEffects
    {
        public int EffectId { get; set; }
        public string EffectName { get; set; }
        public string InstructionName { get; set; }
        public string InstructionMetaData { get; set; }
    }
}
