<?xml version="1.0" encoding="utf-8"?>
<Database Name="HolidayShow" EntityNamespace="HolidayShow.Data" ContextNamespace="HolidayShow.Data" Class="HolidayShowDataContext" EntityBase="LinqEntityBase" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=.;Initial Catalog=HolidayShow;User ID=sa;Password=nicetry" SettingsObjectName="Properties.Settings" SettingsPropertyName="HolidayShowConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AudioOptions" Member="AudioOptions">
    <Type Name="AudioOptions">
      <Column Name="AudioId" Storage="_audioId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileName" Storage="_fileName" Type="System.String" DbType="nvarchar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AudioDuration" Storage="_audioDuration" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsNotVisable" Storage="_isNotVisable" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="AudioOptions_DevicePatternSequences" Member="DevicePatternSequencesList" Storage="_devicePatternSequencesList" OtherKey="AudioId" Type="DevicePatternSequences" DeleteOnNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceIoPorts" Member="DeviceIoPorts">
    <Type Name="DeviceIoPorts">
      <Column Name="DeviceIoPortId" Storage="_deviceIoPortId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeviceId" Storage="_deviceId" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="CommandPin" Storage="_commandPin" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Storage="_description" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsNotVisable" Storage="_isNotVisable" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDanger" Storage="_isDanger" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" />
      <Association Name="DeviceIoPorts_DevicePatternSequences" Member="DevicePatternSequencesList" Storage="_devicePatternSequencesList" OtherKey="DeviceIoPortId" Type="DevicePatternSequences" DeleteOnNull="false" />
      <Association Name="Devices_DeviceIoPorts" Member="Devices" Storage="_devices" ThisKey="DeviceId" Type="Devices" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.DevicePatterns" Member="DevicePatterns">
    <Type Name="DevicePatterns">
      <Column Name="DevicePatternId" Storage="_devicePatternId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeviceId" Storage="_deviceId" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PatternName" Storage="_patternName" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DevicePatterns_DevicePatternSequences" Member="DevicePatternSequencesList" Storage="_devicePatternSequencesList" OtherKey="DevicePatternId" Type="DevicePatternSequences" DeleteOnNull="false" />
      <Association Name="DevicePatterns_SetSequences" Member="SetSequencesList" Storage="_setSequencesList" OtherKey="DevicePatternId" Type="SetSequences" DeleteOnNull="false" />
      <Association Name="Devices_DevicePatterns" Member="Devices" Storage="_devices" ThisKey="DeviceId" Type="Devices" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.DevicePatternSequences" Member="DevicePatternSequences">
    <Type Name="DevicePatternSequences">
      <Column Name="DevicePatternSeqenceId" Storage="_devicePatternSeqenceId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DevicePatternId" Storage="_devicePatternId" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="OnAt" Storage="_onAt" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Duration" Storage="_duration" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AudioId" Storage="_audioId" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DeviceIoPortId" Storage="_deviceIoPortId" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="AudioOptions_DevicePatternSequences" Member="AudioOptions" Storage="_audioOptions" ThisKey="AudioId" Type="AudioOptions" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="DeviceIoPorts_DevicePatternSequences" Member="DeviceIoPorts" Storage="_deviceIoPorts" ThisKey="DeviceIoPortId" Type="DeviceIoPorts" IsForeignKey="true" />
      <Association Name="DevicePatterns_DevicePatternSequences" Member="DevicePatterns" Storage="_devicePatterns" ThisKey="DevicePatternId" Type="DevicePatterns" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Devices" Member="Devices">
    <Type Name="Devices">
      <Column Name="DeviceId" Storage="_deviceId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Devices_DeviceIoPorts" Member="DeviceIoPortsList" Storage="_deviceIoPortsList" OtherKey="DeviceId" Type="DeviceIoPorts" DeleteOnNull="false" />
      <Association Name="Devices_DevicePatterns" Member="DevicePatternsList" Storage="_devicePatternsList" OtherKey="DeviceId" Type="DevicePatterns" DeleteOnNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sets" Member="Sets">
    <Type Name="Sets">
      <Column Name="SetId" Storage="_setId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SetName" Storage="_setName" Type="System.String" DbType="nvarchar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsDisabled" Storage="_isDisabled" Type="System.Boolean" DbType="bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Sets_SetSequences" Member="SetSequencesList" Storage="_setSequencesList" OtherKey="SetId" Type="SetSequences" DeleteOnNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SetSequences" Member="SetSequences">
    <Type Name="SetSequences">
      <Column Name="SetId" Storage="_setId" Type="System.Int32" DbType="int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OnAt" Storage="_onAt" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DevicePatternId" Storage="_devicePatternId" Type="System.Int32" DbType="int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SetSequenceId" Storage="_setSequenceId" Type="System.Int32" DbType="int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DevicePatterns_SetSequences" Member="DevicePatterns" Storage="_devicePatterns" ThisKey="DevicePatternId" Type="DevicePatterns" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Sets_SetSequences" Member="Sets" Storage="_sets" ThisKey="SetId" Type="Sets" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Settings">
      <Column Name="SettingName" Storage="_settingName" Type="System.String" DbType="varchar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ValueString" Storage="_valueString" Type="System.String" DbType="varchar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ValueDouble" Storage="_valueDouble" Type="System.Double" DbType="float NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>