//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayShow.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetSequences
    {
        public int SetSequenceId { get; set; }
        public int SetId { get; set; }
        public int OnAt { get; set; }
        public int DevicePatternId { get; set; }
    
        public virtual DevicePatterns DevicePatterns { get; set; }
        public virtual Sets Sets { get; set; }
    }
}
